### ISSUE TITLE
Manual run does nothing

### ISSUE THREAD

**Issue by k-poole** [MarkDHamill/digests#22]
Hi,

Fresh phpBB 3.1.9 install on PHP 5.6, created some forums, did a few posts, installed this extension, and did a manual run both dated now and in the future, trying both email and file store, and there's no output.

Nothing in the error logs, and all functionality appears otherwise working. Any ideas?

Thanks
-KP

**Comment by MarkDHamill** [comment]
Please leave feedback [here](https://www.phpbb.com/community/viewtopic.php?f=456&t=2354426) so others can share. Also look at [this blog post](https://phpbbservices.com/2016/05/20/why-arent-posts-appearing-in-my-digests/).

**Comment by k-poole** [comment]
Hey

Thanks for the reply. Not using that unless I learn something helpful - 25 pages is arduous. Haha

I realised I missed the cache directory, otherwise it seems fine. After that it started chucking HTTP 500 errors, and the log shows

> [30-Sep-2016 00:25:49 UTC] PHP Fatal error:  Class 'phpbb\cron\task\base' not found in /home/lectech/public_html/ext/phpbbservices/digests/cron/task/digests.php on line 17

Hopefully that helps you :) (FYI this is a clone of master)

Cheers
-KP

**Comment by MarkDHamill** [comment]
In 3.0.5 when you do a manual mailing the option to save the output to files goes into /store/ext/phpbbservices/digests. The permissions should be world writeable for the store folder.

**Comment by k-poole** [comment]
Yep that it is:
drwxrwxrwx  3 lectech lectech 4.0K Sep 29 13:43 store

**Comment by k-poole** [comment]
FYI latest commits appear to 500 when manually running.

error_log:

> [03-Oct-2016 02:07:46 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTimeZone::__construct(): Unknown or bad timezone ()' in /home/lectech/public_html/ext/phpbbservices/digests/core/common.php:61
> Stack trace:
> #0 /home/lectech/public_html/ext/phpbbservices/digests/core/common.php(61): DateTimeZone->__construct('')
> #1 /home/lectech/public_html/ext/phpbbservices/digests/cron/task/digests.php(620): phpbbservices\digests\core\common->make_tz_offset('', 'k_poole')
> #2 /home/lectech/public_html/ext/phpbbservices/digests/cron/task/digests.php(264): phpbbservices\digests\cron\task\digests->mail_digests(1475460466, -74)
> #3 [internal function]: phpbbservices\digests\cron\task\digests->run()
> #4 /home/lectech/public_html/phpbb/cron/task/wrapper.php(104): call_user_func_array(Array, Array)
> #5 /home/lectech/public_html/cron.php(64): phpbb\cron\task\wrapper->__call('run', Array)
> #6 /home/lectech/public_html/cron.php(64): phpbb\cron\task\wrapper->run()
> #7 {main}
>   thrown in /home/lectech/public_html/ext/phpbbservices/digests/core/common.php on line 61

Cheers
-KP

**Comment by MarkDHamill** [comment]
Set your timezone in the User Control Panel. You probably just set up the forum and are trying to run digests with an Admin username. If your timezone is not set and you try to subscribe to digests in the UCP, it will detect this and tell you to set it first.

Regardless, before manually running digests you need to subscribe to receive a digest.

**Comment by k-poole** [comment]
Hey mate

Yep I manually subscribed all users to the digest, and went over all configuration options to make sure nothing was missed.

The board default timezone was set, just set it for my own user though. Perhaps if user has no timezone set, instead of PHP bailing and the browser throwing a HTTP 500, you could default to board guest timezone?

That did it though. Thanks heaps!

**Comment by MarkDHamill** [comment]
What you experience is a bug in phpBB. Users select a timezone when they register but when setting up phpBB the default admin account has none. I reported it: https://tracker.phpbb.com/browse/PHPBB3-14404?filter=-2

**Comment by k-poole** [comment]
Ah okay - same for manual account creation it appears! Cheers.

**Comment by MarkDHamill** [comment]
If you mean an add users extension, it may have this issue. When a user goes through the normal registration system, they pick their timezone. I believe it defaults to the board timezone.

**Comment by MarkDHamill** [comment]
Since a new release is pending I added a change that should fix this problem. https://github.com/MarkDHamill/digests/commit/8c4e3cd244808ff6194f8465365ca7f57028be5f
