### ISSUE TITLE
info_acp_common.php - Line 135

### ISSUE THREAD

**Issue by Praggle** [MarkDHamill/digests#28]
You wrote:
	

'DIGESTS_SHOW_EMAIL_EXPLAIN'							=> 'If this is enabled, the subscriber&apos;s email address is shown in entries in the admin log by the username of the subscriber. This can be useful in troubleshooting **digest issues mailer issues**.',

Probably you ment:

'DIGESTS_SHOW_EMAIL_EXPLAIN'							=> 'If this is enabled, the subscriber&apos;s email address is shown in entries in the admin log by the username of the subscriber. This can be useful in troubleshooting **digest mailer issues**.',

**Comment by Praggle** [comment]
Translation is set up in my new fork. I hope, this is now the way that was intended.

**Comment by MarkDHamill** [comment]
Thanks Praggle. I'll make the correction. Editing was never my strong suit.

**Comment by MarkDHamill** [comment]
I may publicize translation links in the README.

**Comment by 3D-I** [comment]
Yes, or Praggle should delete everything from his fork except for those files (inclusive folders) involved into the translation job, so to have a repository that just contains the translated files within their own folder.

This way, a simple link to the D/L package does the final trick.

i.e.: **/lang/de/blah.php**

Praggle could, in the future (in case), commit new changes to those files after having created a branch and provide the new D/L link.

My 2€cents

**Comment by Praggle** [comment]
I have deleted everything except my german language folders. And when you have created a new RC-branch I will create also a new RC-branch with the changed translation folder. I hope this is, what you've meant. I will try.

**Comment by 3D-I** [comment]
Yes, it is.

**Comment by MarkDHamill** [comment]
Are we good? Can I close this issue?

**Comment by 3D-I** [comment]
Looks good to me.
