### ISSUE TITLE
Error log: Error while creating image

### ISSUE THREAD

**Issue by gRegorLove** [MarkDHamill/digests#49]
Error message in logs: Error in [ROOT]/ext/phpbbservices/digests/cron/task/digests.php on line 576: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

Digests version: 3.2.16
PHP version: 7.3.11

**Comment by MarkDHamill** [comment]
This version was written for PHP 3.2, which supports up to PHP 7.2. This is likely an issue that I will need to address in a 3.3 compatible version. You can downgrade PHP to 7.2 and you should be okay.

**Comment by gRegorLove** [comment]
@MarkDHamill Thanks for the quick reply! I figured this is probably a PHP warning/notice and isn't affecting the functionality of the module. Does that sound correct? If so I'm okay running it as-is.

**Comment by MarkDHamill** [comment]
The extension should not install on phpBB 3.3, at least without some juryrigging which I assume you didn't do. I'll have to analyze the issue once I have a test environment set up again to see if this is something I missed.

**Comment by gRegorLove** [comment]
@MarkDHamill I'm running phpBB 3.2.8 so the install went smoothly. I am experiencing some (unrelated, I think) issues with the emails being delivered. I noticed this error message as I was debugging that.

**Comment by MarkDHamill** [comment]
You are correct. Those should be continue 2 statements, for weekly, monthly and daily digests. This bug fix will show up in the next version. You might want to make these changes.

**Comment by gRegorLove** [comment]
Fixed in [3.2.17](https://www.phpbb.com/customise/db/extension/digests_extension/support/topic/212946). Thanks!
