### ISSUE TITLE
Issue with php 8.0.1

### ISSUE THREAD

**Issue by sslorigin** [MarkDHamill/digests#60]
Hi
I'v got an error message by wanting to **Edit subscribers** in the ACP
Digests version 3.3.4

`[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool
[phpBB Debug] PHP Warning: in file [ROOT]/ext/phpbbservices/digests/acp/main_module.php on line 744: Trying to access array offset on value of type bool`

![Capture d’écran 2021-02-09 à 15 12 24](https://user-images.githubusercontent.com/69965579/107375771-64714080-6ae9-11eb-8651-b55571400b5a.png)

**Comment by MarkDHamill** [comment]
This is a known bug that will be fixed in the next release. It can happen if there are no forums. Try changing line 650 to:

`					if (isset($allowed_forums) && is_array($allowed_forums) && count($allowed_forums) > 0)`

**Comment by sslorigin** [comment]
Thanks for your réponse but it doesn't change anything

**Comment by MarkDHamill** [comment]
The extension has not been tested with PHP 8 yet. You might want to downgrade PHP.

**Comment by sslorigin** [comment]
Nope i don't downgrade my php version, i'll wait for the next update.
Thank you Mark

**Comment by MarkDHamill** [comment]
Try replacing lines 744-755 in /acp/main_module.php from:

```
						// Now out of the loop, it is important to remember to close any open <div> tags. Typically there is at least one.
						while ((int) $row2['parent_id'] !== (int) end($parent_stack))
						{
							array_pop($parent_stack);
							$current_level--;
							// Need to close the <div> tag
							$this->template->assign_block_vars('digests_edit_subscribers.forums', array(
								'S_DIV_CLOSE' 	=> true,
								'S_DIV_OPEN' 	=> false,
								'S_PRINT' 		=> false,
								)
							);
						}
```

to 

```
						// Now out of the loop, it is important to remember to close any open <div> tags. Typically there is at least one.
						if (isset($row2) && is_array($row2))
						{
							while ((int) $row2['parent_id'] !== (int) end($parent_stack))
							{
								array_pop($parent_stack);
								$current_level--;
								// Need to close the <div> tag
								$this->template->assign_block_vars('digests_edit_subscribers.forums', array(
										'S_DIV_CLOSE' 	=> true,
										'S_DIV_OPEN' 	=> false,
										'S_PRINT' 		=> false,
									)
								);
							}
						}
```

The reason why this fails is ultimately the same. The user with focus in Edit Subscribers has no forum permissions, i.e. cannot see any forums on the index. If no forums are defined for your board this error should have occurred. You might want to check the user's group forum permissions: ACP > Permissions > Group forum permissions. All forum permissions for the user or group must be set to NEVER (similar to No role defined) for this to be triggered. If they go to the index, they will see a "This board has no forums" error message. In addition, in Edit Subscribers no list of forums can appear for the administrator to check or uncheck for this user.

**Comment by sslorigin** [comment]
Thanks Mark
All is good now.
