### ISSUE TITLE
Beta-Branch as new default

### ISSUE THREAD

**Issue by Praggle** [MarkDHamill/digests#9]
Maybe you can change the tree as suggested by 3Di [here](https://www.phpbb.com/community/viewtopic.php?f=456&t=2354426&start=105#p14379601) and than set the new beta branch as default. See: [Setting the default branch](https://help.github.com/articles/setting-the-default-branch/)

**Comment by MarkDHamill** [comment]
I do want Master to be the default branch. Beta is supposed to be a snapshot for the Beta release. Any bugs found or additions to the Beta will need to be rolled back into the Master at some point.

As I am new to CM it's quite possible this is not the best approach.
